### ISSUE TITLE
Unable to Verify Blockstack ID LinkedIn Account

### ISSUE THREAD

**Issue by ChristopherA** [blockstack/blockstack-browser#1060]
I have posted at https://www.linkedin.com/pulse/blockstack-id-christopher-allen/ my blockstack info but when I click verify it continues to display as unverified. Returning a day later, still unverified.

**Comment by cryptorico** [comment]
#metoo

**Comment by larrysalibra** [comment]
So sorry about this issue @ChristopherA @jackzampolin if you have a second, can you take a look at @ChristopherA 's verification and see why it might be failing?

**Comment by jackzampolin** [comment]
It looks like he has posed the verification on Linkedin Pulse. I think this might be the issue.

**Comment by ChristopherA** [comment]
I went to where the app sent me ;-)

**Comment by ChristopherA** [comment]
Today's version of the Blockstack Browser up, for the LinkedIn verification, sends me to https://www.linkedin.com/feed/ which is where I posted my https://www.linkedin.com/pulse/blockstack-id-christopher-allen/ — what is the correct place to post my verification?

**Comment by yknl** [comment]
Hey @ChristopherA, when you go to https://www.linkedin.com/feed do you see this?
![image](https://user-images.githubusercontent.com/29081231/35112730-e8a0dfbe-fc4c-11e7-9e80-244e57aa3433.png)

If you paste the verification message there and then press **post**, it should make the correct verification post you need.

**Comment by ChristopherA** [comment]
That is how I posted https://www.linkedin.com/pulse/blockstack-id-christopher-allen/

**Comment by yknl** [comment]
The verification system expects the message in an "Update" format. Your posts might be posted to LinkedIn pulse because you have an influencer account. Does LinkedIn offer you a way for you to just "Share an update"?

**Comment by TonyGranato** [comment]
Dear all, I do have the same problem like Christopher. Any news to solve this issue?

**Comment by jiggaross** [comment]
Also having the same problem with the current LinkedIn verification. Any suggestions on troubleshooting this?

**Comment by moxiegirl** [comment]
@jiggaross Sorry you are having problems.  There is an underlying issue with the LinkedIn verification.  It was supposed to be removed.  Apologies for the confusion.

**Comment by moxiegirl** [comment]
Just an FYI @yknl I've tried both the "post" format and the "update" format, neither is working.

**Comment by pascalgbouvier** [comment]
i have the same issue. posted proof on Linkedin at https://www.linkedin.com/feed/update/urn:li:activity:6482353835326132224 and try as i might no verification occurs.

**Comment by sposth** [comment]
I am not entirely sure if this is the reason, the verification does not work: but LinkedIn is using a proprietary URL shortener. Every posted URL will be shortened when publishing the post. So it will - in general - not be possible for external applications to verify the URL.

**Comment by sylvandb** [comment]
and today still the problem exists https://www.linkedin.com/feed/update/urn:li:activity:6501520582562189314/  is my post, yet not verified.  (twitter and github did verify, but linkedin...  not so much)

**Comment by sposth** [comment]
I don't think it is possible - at all - to verify the LinkedIn ID. Due to the way LinkedIn deals with URL's.
Not sure if anyone from Blockstack is taking a look at this issue. Maybe, it is not that important.

**Comment by sylvandb** [comment]
It obviously isn't important enough to remove it from the page so people don't waste time trying.

I wonder what was more important?

The shortened tracker/redirect link seems to appear only for non-auth'ed access, and `curl` appears to follow it just fine. And the hash is still present in the body of the message. I don't see any particular technical challenge in making that validation work, and it would be trivial for a person to do that validation instead of "all those keep trying" responses I found with google. The time I wasted before finding this bug thread was way longer than it would take someone familiar with the codebase to remove the linked in option from the UI (and I'm horrible at UI). It seems likely the time I spent would have been enough time for that person to instead fix the problem and when you figure the time spent by the folks who posted here (ignoring anyone else that may have wasted time on it)...

**Comment by lord-aerion** [comment]
I just ran into this issue as well. I can't believe an issue like this is still unresolved after nearly one and a half years. Either fix it, or mark it as "won't fix" and remove the option altogether. This is just wasting people's time.

**Comment by otech47** [comment]
If it's worth anything there wouldn't actually be any code in this repo to change since everything seems to be running fine until the [validateProofsService function](https://github.com/blockstack/blockstack-browser/blob/master/app/js/profiles/store/identity/actions.js#L24) is invoked. Then a call to `validateProofs` from the blockstack.js module is what should return the linkedin proof with `valid: true` but it always seems to come back false. 

Need to dig some more into the [validateProof function](https://github.com/blockstack/blockstack.js/blob/master/src/profiles/services/service.js#L6) in blockstack.js to understand what special parsing is needed to handle the shortened `lnkd.in` URL

Also https://github.com/blockstack/blockstack.js/issues/550 is likely related

**Comment by otech47** [comment]
Should be fixed with https://github.com/blockstack/blockstack.js/pull/635 but if it is merged and deployed, blockstack-browser would need to update the blockstack.js version for this issue to be closed out

**Comment by lord-aerion** [comment]
Is there any update on this? My LinkedIn status still shows up as _Unverified_, even after creating a new post with the requested text and updating the URL of the post.

**Comment by otech47** [comment]
> Is there any update on this? My LinkedIn status still shows up as _Unverified_, even after creating a new post with the requested text and updating the URL of the post.

@lord-aerion the pre-release for v0.36.1 of the blockstack-browser installs [blockstack@18.3.0](https://github.com/blockstack/blockstack-browser/blob/v0.36.1/package-lock.json#L2627) as a dependency which doesn't have blockstack/blockstack.js#635 merged in yet.

When blockstack-browser has bumped the version on blockstack.js then this should be fixed.

**Comment by lord-aerion** [comment]
OK, thanks. Is there a time frame for this? I'd hoped that waiting a month and a half since the last update would have seen the fix implemented.

Don't get me wrong, it's great to see that two and half years since the issue was first reported a fix is actually in the works, but it just feels like it's dragging on unnecessarily.

**Comment by otech47** [comment]
Not sure how long it usually takes to bump the blockstack version for the browser especially for a major version but maybe @zone117x @yknl can give a better idea

**Comment by justindthomas** [comment]
Still apparently an issue? I tried to re-verify since my verification from some years back stopped working. No luck.

**Comment by larrysalibra** [comment]
@justindthomas I'm not aware of any work that's been done on the linkedin proof.

**Comment by larrysalibra** [comment]
I think we should consider removing LinkedIn as an option - it seems too problematic to keep

**Comment by MichaelSaucier** [comment]
Same issues.  I cannot verify on either LinkedIn or Instagram.  Followed directions meticulously.
