### ISSUE TITLE
npm install fail on web-0.3 branch

### ISSUE THREAD

**Issue by cstrangedk** [blockstack/blockstack-browser#200]
This is still happening on the `web-0.3` branch.  Ref: #199 and #125 

**Steps to reproduce:**
`git clone https://github.com/blockstack/blockstack-browser.git -b web-0.3`
`npm install`

**Error:**

`npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Cloning into bare repository '~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494'...
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Permission denied (publickey).
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: fatal: Could not read from remote repository.
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494:
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Please make sure you have the correct access rights
npm ERR! git clone --template=~/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git ~/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: and the repository exists.
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) Permission denied (publickey).
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) fatal: Could not read from remote repository.
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git)
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) Please make sure you have the correct access rights
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) and the repository exists.`

**Comment by guylepage3** [comment]
@shea256 I am assigning this issue to you

**Comment by shea256** [comment]
@cstrangedk Thanks for reporting!

I just pushed an update to some libraries that should have addressed the issue.

Closing the issue but please let me know if it's working for you now and if it's not, please reopen.

Thanks!

**Comment by cstrangedk** [comment]
@shea256 just reinstalled, but I am still receiving an error on `ssh://git@github.com/shea256/bitcoinjs-lib.git`

**Comment by drhetnet** [comment]
I am also getting similar errors when trying npm install (on master, web-0.3 and web-0.2):
```
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/bitcoinjs-lib.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-bitcoinjs-lib-git-33ec648a: Cloning into bare repository '/home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-bitcoinjs-lib-git-33ec648a'...
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/bitcoinjs-lib.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-bitcoinjs-lib-git-33ec648a: Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/bitcoinjs-lib.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-bitcoinjs-lib-git-33ec648a: Permission denied (publickey).
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/bitcoinjs-lib.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-bitcoinjs-lib-git-33ec648a: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/bitcoinjs-lib.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-bitcoinjs-lib-git-33ec648a: 
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/bitcoinjs-lib.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-bitcoinjs-lib-git-33ec648a: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/bitcoinjs-lib.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-bitcoinjs-lib-git-33ec648a: and the repository exists.
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Cloning into bare repository '/home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494'...
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Permission denied (publickey).
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: 
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/jason/.npm/_git-remotes/_templates --mirror ssh://git@github.com/shea256/ecurve.git /home/jason/.npm/_git-remotes/git-ssh-git-github-com-shea256-ecurve-git-cd23c494: and the repository exists.

```

**Comment by drhetnet** [comment]
Found a workaround for the repos that won't install (in case anyone else ends up with same problem). Install both manually:
`sudo npm install -G -S "git+https://drhetnet@github.com/shea256/bitcoinjs-lib.git"
sudo npm install -G -S "git+https://drhetnet@github.com/shea256/ecurve.git"`

then go into the package.json file and remove them as dependencies. npm install should work.
