### ISSUE TITLE
Add redirect support to CORS proxy 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#211]
The CORS proxy doesn't follow redirects and can sometimes cause problems.  (example https://github.com/blockstack/blockstack-browser/issues/146)

Let's investigate adding redirect support.

**Comment by jackzampolin** [comment]
Looks like this has been solved.

**Comment by larrysalibra** [comment]
As far as I know it still doesn't support redirects, but as of now, this hasn't appeared to be a problem. It might be a problem with verifications (example: if someone puts a verification from m.facebook.com and then someone tries to verify it on a platform or network that redirects m.facebook.com to www.facebook.com)

We can re-open this if we see that problem
