### ISSUE TITLE
Error signing into blockstack todo

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-browser#734]
```
main.js:3403 Uncaught TypeError: Cannot read property 'appsNodeKey' of undefined
    at AuthModal.login (main.js:3403)
    at Object.invokeGuardedCallback (main.js:125273)
    at executeDispatch (main.js:119310)
    at Object.executeDispatchesInOrder (main.js:119330)
    at executeDispatchesAndRelease (main.js:118741)
    at executeDispatchesAndReleaseTopLevel (main.js:118752)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (main.js:130661)
    at Object.processEventQueue (main.js:118952)
    at runEventQueueInBatch (main.js:125340)
```

**Comment by jackzampolin** [comment]
Error coming from https://github.com/blockstack/blockstack-browser/blob/master/app/js/auth/components/AuthModal.js#L119

**Comment by jackzampolin** [comment]
Another report from @jay-hwang:

https://github.com/blockstack/blockstack-browser/issues/735

**Comment by pauldariye** [comment]
I'm having a similar issue. Unable to sign in to any of the apps.

**Comment by jackzampolin** [comment]
Can you update your browser to the latest release (`0.15.0`) I'm fairly sure this is fixed in master

**Comment by pauldariye** [comment]
Updated and still unable to sign in to any of the apps with version `0.15.0`

**Comment by Pkmember** [comment]
Hey 👋 I have the exact same issue with Blockstack browser 0.15.0

**Comment by kantai** [comment]
I experience this issue with a wiped local storage, after I restore my account. When trying to login to helloblockstack, I get the error, which seems to be caused by this bit of code:

```
var profileSigningKeypair = this.props.identityKeypairs.find(function (keypair) {
        return keypair.address === localIdentities[userDomainName].ownerAddress;
});
```

The entry in `localIdenties` corresponding to the name has no `ownerAddress` attribute, so this lookup fails to find a keyPair.

**Comment by kantai** [comment]
Okay -- in the latest release of blockstack-browser, this is fixed for me -- I think the problem before was that the old keychain was still hanging around in the browser after a restore. 

In the new version, the old keychain has to be deleted first, and then you restore through the initial on-boarding dialogues:

![screenshot from 2017-09-11 11-15-59](https://user-images.githubusercontent.com/1153552/30282303-deb22fe6-96e2-11e7-9bf3-b6e886a51cbe.png)


People who have had difficulty logging in after restoring accounts should use that process.

**Comment by larrysalibra** [comment]
Glad to hear it is working for you now @kantai. 

The process for removing and restoring your account is:

1. Make sure you've written down your identity key backup phrase
2. In the Blockstack Browser, go to settings -> remove account and remove your account
3) Restore your account through the option in the onboarding screen that appears after step (seen in @kantai's screenshot above)

**Comment by jackzampolin** [comment]
This is fixed in the latest release. Closing.
